using UnityEngine;

public class human : MonoBehaviour
{
    public float horizontalInput;
    public float verticalInput;
    public float speed = 10;
    public GameObject prefab;
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        horizontalInput = Input.GetAxis("Horizontal");
        transform.Translate(Vector3.right * horizontalInput * Time.deltaTime * speed);
        verticalInput = Input.GetAxis("Vertical");
        transform.Translate(Vector3.forward * verticalInput * Time.deltaTime * speed);

        float spawnDistance = 1.5f;
        if (Input.GetKeyDown(KeyCode.Space))
        {
            Instantiate(prefab, transform.position + transform.forward * spawnDistance, prefab.transform.rotation);
        }
    }
}
